### ISSUE TITLE
Disable erroneous functionality/commands in multivm setup

### ISSUE THREAD

**Issue by jgriegershs** [Siemens-Healthineers/K2s#457]
### Problem
After migrating to the new PS structure (https://github.com/Siemens-Healthineers/K2s/issues/265), functionality for multivm setup is missing or errouneous (e.g. `k2s addons export dashboard`).

### Solution
It was decided to *disable* the erroneous/missing functionality and display an explanation message instead due to the fact that multivm and other known setup types will be deprecated soon (see https://github.com/Siemens-Healthineers/K2s/issues/63 and  https://github.com/Siemens-Healthineers/K2s/issues/133).

Commands known to be not working in multivm:
- image
  - [x] pull -w
  - [x] build
  - [x] clean
  - [x] export
  - [x] import -w
  - [x] registry (add/switch)
  - [x] rm
- addons
  - [x] export/import
  - [x] enable (dashboard, exthttpaccess, gateway-nginx, ingress-nginx, logging, monitoring, registry, smb-share, traefik)
- system
  - [x] `k2s system scp m /tmp/addons.zip c:\temp\addons\test\ -r -o` or `k2s system scp m /tmp/addons.zip c:\temp\addons\test\addons.zip -r -o` does nothing (no error) when target dir does not exist. To be tested in non-multivm installation -> see #498 
  - [x] `k2s system scp m C:\Temp\addons\test\addons.zip /tmp/test -o` does nothing (no error) when source dir does not exist. To be tested in non-multivm installation  -> see #498 
  - [x] `k2s system scp m C:\Temp\addons\addons.zip /tmp/test` does create a file called *test* if this dir does not exist. To be tested in non-multivm installation  -> see #498 
  - [x] `k2s system scp w C:\Temp\addons\addons.zip c:\temp\addons.zip` failes but reports *SUCCESS* when target dir does not exist. Also, it creates a file called *Temp* in this case.
  - [x] `k2s system scp w C:\Temp\addons.zip C:\Temp\addons\test\addons.zip -r -o` failes when target dir does not exist, but reports *SUCCESS*
  - [x] `k2s system scp w C:\Temp\addons.zip C:\Temp\addons\test\addons.zip -r -o` failes when source file does not exist, but reports *SUCCESS*
  - [x] `k2s system reset` uninstalls *K2s*, but leaves the control-plane VM in *Off* status and the *Windows* worker VM running
  - [x] `k2s system upgrade` does not work
